authapp/urls.py
from django.urls import path, include

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
]

mainapp/urls.py
from django.urls import path, include

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('catalog/', mainapp.catalog, name='catalog'),
    path('about1/', mainapp.about1, name='about1'),
    path('about2/', mainapp.about2, name='about2'),
    path('about3/', mainapp.about3, name='about3'),
    path('info/<int:id>/', mainapp.get_product, name='info'),
]

tehplan45/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from tehplan45 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('accounts/', include('authapp.urls', namespace='authapp')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models

from authapp.models import User


class News(models.Model):
    title = models.CharField(verbose_name='Заголовок', max_length=256)
    content = models.TextField(verbose_name="Контент")
    image = models.ImageField(verbose_name='изображение', upload_to='news/%Y/%m/%d')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'


class Comments(models.Model):
    class Status(models.TextChoices):
        ZERO = '0', 'заблокирован',
        FIRST = '1', 'Опубликован',
        TWO = '2', ' Ожидает проверки'

    news = models.ForeignKey(News, verbose_name='новость', on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    comment = models.TextField(verbose_name='комментарий')
    status = models.CharField(verbose_name='статус', max_length=1, choices=Status.choices, default=Status.ZERO)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'комментарий'
        verbose_name_plural = 'комменатрии'


class Favorite(models.Model):
    news = models.ForeignKey(News, verbose_name='Новость', on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранные'




class Products(models.Model):
    name = models.CharField(verbose_name='Название товара', max_length=128)
    image = models.ImageField(verbose_name='Изображение товара', upload_to='products/%Y/%m/%d')
    price = models.DecimalField(verbose_name='Цена', max_digits=10, decimal_places=2)
    info = models.TextField(verbose_name='Информация', default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

class FeedBack(models.Model):
    product = models.ForeignKey(Products, verbose_name='Выберите продукт для заказа',on_delete=models.CASCADE)
    address = models.CharField(verbose_name='Адрес объекта недвижимости', max_length=256)
    full_name = models.CharField(verbose_name='ФИО', max_length=100)
    tel = models.IntegerField(verbose_name='Телефон')
    email = models.EmailField(verbose_name='email')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.full_name}{self.email}'

    class Meta:
        ordering = ['-created_at']
        verbose_name = ' Обратная связь'

mainapp/forms.py
from django.forms import forms, ModelForm

from mainapp.models import FeedBack


class FeedbackForm(ModelForm):
    class Meta:
        model = FeedBack
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['address'].widget.attrs['placeholder'] = 'Адресс объекта недвижимости: '
        self.fields['product'].widget.attrs['placeholder'] = 'Выберите продукт для заказа: '
        self.fields['full_name'].widget.attrs['placeholder'] = 'ФИО: '
        self.fields['tel'].widget.attrs['placeholder'] = 'Телефон: '
        self.fields['email'].widget.attrs['placeholder'] = 'E-mail: '
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            field.label = ''

mainapp/views.py
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from mainapp.forms import FeedbackForm
from mainapp.models import Products
from tehplan45 import settings


def index(request):
    products = Products.objects.all()[:6]
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            messages = f'От: ({form.email})\n ' \
                       f'Имя: {form.full_name} ({form.tel})\n ' \
                       f'Товар: {form.product} \n ' \
                       f'Адрес: {form.address} \n '
            res = send_mail(settings.EMAIL_TITLE, messages, settings.EMAIL_HOST_USER, ['crimecrew_tehplan@mail.ru'])
            if res:
                form.save()
            return HttpResponseRedirect(reverse('mainapp:index'))
    else:
        form = FeedbackForm()
    context = {
            'form': form,
            'products': products
    }

    return render(request, 'mainapp/index.html', context)


def catalog(request):
    products = Products.objects.all()
    context = {
        'title': 'каталог',
        'products': products,
    }
    return render(request, 'mainapp/catalog.html', context)


def about1(request):
    context = {
        'title': 'каталог',
    }
    return render(request, 'mainapp/about1.html', context)


def about2(request):
    context = {
        'title': 'каталог',
    }
    return render(request, 'mainapp/about2.html', context)


def about3(request):
    context = {
        'title': 'каталог',
    }
    return render(request, 'mainapp/about3.html', context)


def cart(request):
    if request.user.is_authenticated:
        pass


def get_product(request, id):
    info = get_object_or_404(Products, id=id)
    context = {
        'title': info.name,
        'product': info,
    }
    return render(request, 'mainapp/info.html', context)

mainapp/templates/mainapp/about1.html
{% extends 'mainapp/base.html' %}
{% load static %}
</head>
<body>
{% block content %}
<div class="container">
    <div class="b1">
        <div class="logo">
            <div class="logo_class"><img class="logot" src="img/logo2.png" alt=""></div>
            <div class="text20 mt-3">Снять с учета сгоревший объект.</div>
        </div>
        <h15 class="text21"> Пожары в Курганской области - это наша общая беда. Мы хотим помочь жителям Кургана,
            Кетовского и
            Белозерского районов, у которых пожар уничтожил дом, баню, гараж или иное зарегистрированное недвижимое
            имущество. Мы подготовим документы для снятия с кадастрового учета объектов и не возьмем денег за это.
            Почему мы это делаем тут. Заполните заявку на подготовку документов и мы свяжемся с вами в рабочее время.
            Еще раз - это бесплатно.
        </h15>
    </div>
    <div class="input_class ">
        <div class="input1">
            <div class="text22">
                <h17 style="font-size: 25px; font-weight: bold;">Бесплатная заявка</h17>
                <h16>на оформление документов для снятия с учета</h16>
            </div>
            <input class="tb1" type="" placeholder="Адрес объекта недвижимости" required/>
            <input class="tb1" type="name" placeholder="ФИО" required="required">
            <input class="tb1" type="tel" placeholder="Телефон"
                   pattern="+([0-9]{1,3})(\([0-9]{2,3}\))-([0-9]{3})-([0-9]{2})-([0-9]{2})">
            <input class="tb1" type="" placeholder="E-mail">
            <div class="text8">Нажимая кнопку «Отправить», я даю свое согласие на обработку моих персональных данных, в
                соответствии с <br> Федеральным законом от 27.07.2006 года №152-ФЗ «О персональных данных», на условиях
                и для целей, определенных в<br> Согласии на обработку персональных данных *
            </div>
            <button class="b_order_2">
                <p class="text-btn">Оставить заявку</p>
            </button>
        </div>
    </div>



    <div class="modal fade " id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false"
         tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Готово!</h5>
                </div>
                <div class="modal-body">
                    Ваша заявка успешно отпавлена.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/about2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css.css">
</head>
<body>
<div class="container">
    <div class="b1">
        <div class="logo">
            <div class="logo_class"><img class="logot" src="img/logo2.png" alt=""></div>
            <div class="text20 mt-3">Снять с учета сгоревший объект.</div>
        </div>
        <h15 class="text21"> Пожары в Курганской области - это наша общая беда. Мы хотим помочь жителям Кургана,
            Кетовского и
            Белозерского районов, у которых пожар уничтожил дом, баню, гараж или иное зарегистрированное недвижимое
            имущество. Мы подготовим документы для снятия с кадастрового учета объектов и не возьмем денег за это.
            Почему мы это делаем тут. Заполните заявку на подготовку документов и мы свяжемся с вами в рабочее время.
            Еще раз - это бесплатно.
        </h15>
    </div>
    <div class="input_class">
        <div class="input1">
            <div class="text22">
                <h17 style="font-size: 25px">Бесплатная заявка</h17>
                <h16>на оформление документов для снятия с учета</h16>
            </div>
            <input class="tb1" type="" placeholder="Адрес объекта недвижимости" required/>
            <input class="tb1" type="name" placeholder="ФИО" required="required">
            <input class="tb1" type="tel" placeholder="Телефон"
                   pattern="+([0-9]{1,3})(\([0-9]{2,3}\))-([0-9]{3})-([0-9]{2})-([0-9]{2})">
            <input class="tb1" type="" placeholder="E-mail">
            <div class="text8">Нажимая кнопку «Отправить», я даю свое согласие на обработку моих персональных данных, в
                соответствии с <br> Федеральным законом от 27.07.2006 года №152-ФЗ «О персональных данных», на условиях
                и для целей, определенных в<br> Согласии на обработку персональных данных *
            </div>
            <button class="b_order_2" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                <h9>Оставить заявку</h9>
            </button>
        </div>
    </div>



    <div class="modal fade " id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false"
         tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Готово!</h5>
                </div>
                <div class="modal-body">
                    Ваша заявка успешно отпавлена.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>
    <div class="kub5">
        <div class="tkub">
            <div class="text15">ХОТИТЕ ОБСУДИТЬ<br> ЗАКАЗ ЛИЧНО?</div>
            <div class="text17">Приезжайте к нам в офис:</div>
            <div class="text16">
                Курганская область г.Курган<br> ул.Советская, д.51<br></div>
            <div class="text18"> Телефон: +7 3522 46-07-08</div>
            <div class="text19"> ОГРНИП 316450100051703</div>

        </div>
    </div>

</div>
<div id="map" class="map1">
    <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A4d4a381788fd6f28f29538f1a79e4b52b392d5713c22b4a796360d9642051c75&amp;source=constructor"
            width="100%" height="700" frameborder="0"></iframe>
</div>
</div>
</body>
</html>>

mainapp/templates/mainapp/about3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css.css">
</head>
<body>
<div class="container">
    <div class="b1">
        <div class="logo">
            <div class="logo_class"><img class="logot" src="img/logo2.png" alt=""></div>
            <div class="text20 mt-3">Снять с учета сгоревший объект.</div>
        </div>
        <h15 class="text21"> Пожары в Курганской области - это наша общая беда. Мы хотим помочь жителям Кургана,
            Кетовского и
            Белозерского районов, у которых пожар уничтожил дом, баню, гараж или иное зарегистрированное недвижимое
            имущество. Мы подготовим документы для снятия с кадастрового учета объектов и не возьмем денег за это.
            Почему мы это делаем тут. Заполните заявку на подготовку документов и мы свяжемся с вами в рабочее время.
            Еще раз - это бесплатно.
        </h15>
    </div>
    <div class="input_class">
        <div class="input1">
            <div class="text22">
                <h17 style="font-size: 25px">Бесплатная заявка</h17>
                <h16>на оформление документов для снятия с учета</h16>
            </div>
            <input class="tb1" type="" placeholder="Адрес объекта недвижимости" required/>
            <input class="tb1" type="name" placeholder="ФИО" required="required">
            <input class="tb1" type="tel" placeholder="Телефон"
                   pattern="+([0-9]{1,3})(\([0-9]{2,3}\))-([0-9]{3})-([0-9]{2})-([0-9]{2})">
            <input class="tb1" type="" placeholder="E-mail">
            <div class="text8">Нажимая кнопку «Отправить», я даю свое согласие на обработку моих персональных данных, в
                соответствии с <br> Федеральным законом от 27.07.2006 года №152-ФЗ «О персональных данных», на условиях
                и для целей, определенных в<br> Согласии на обработку персональных данных *
            </div>
            <button class="b_order_2" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                <h9>Оставить заявку</h9>
            </button>
        </div>
    </div>



    <div class="modal fade " id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false"
         tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Готово!</h5>
                </div>
                <div class="modal-body">
                    Ваша заявка успешно отпавлена.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>
    <div class="kub5">
        <div class="tkub">
            <div class="text15">ХОТИТЕ ОБСУДИТЬ<br> ЗАКАЗ ЛИЧНО?</div>
            <div class="text17">Приезжайте к нам в офис:</div>
            <div class="text16">
                Курганская область г.Курган<br> ул.Советская, д.51<br></div>
            <div class="text18"> Телефон: +7 3522 46-07-08</div>
            <div class="text19"> ОГРНИП 316450100051703</div>

        </div>
    </div>

</div>
<div id="map" class="map1">
    <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A4d4a381788fd6f28f29538f1a79e4b52b392d5713c22b4a796360d9642051c75&amp;source=constructor"
            width="100%" height="700" frameborder="0"></iframe>
</div>
</div>
</body>
</html>

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
     <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Title</title>

    <link href='{% static 'css/bootstrap.min.css' %}' rel="stylesheet">
    <link href='{% static 'css/media.css' %}' rel="stylesheet">
    <link href='{% static 'css/css.css' %}' rel="stylesheet">

    <link rel="shortcut icon" href="img/favicon-32x32%201.png" type="image/x-icon">

</head>
<body>
<div class="b1">
    <div class="container">
        <nav class="navbar navbar-expand-lg " style="height: 70px; background: black">
            <div class="container">
                <a class="navbar-brand" href="{% url 'mainapp:index' %}"><img src="{% static 'img/logo8.png' %}" alt=""></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" aria-current="page" href="{% url 'mainapp:index' %}">Главная</a>
                        <a class="nav-link" aria-current="page" href="{% url 'mainapp:index' %}#service">Услуги</a>
                        <a class="nav-link" aria-current="page" href="{% url 'mainapp:catalog' %}">Каталог</a>
                        <a class="nav-link" aria-current="page" href="{% url 'mainapp:index' %}#map">Контакты</a>
                        <a class="nav-link" aria-current="page" href="{% url 'mainapp:index' %}#o_nas">О нас</a>
                        {#                        <a class="nav-link number" aria-current="page">+7 3522 46-07-08</a>#}
                        {% if not user.is_authenticated %}
                            <a class="nav-link number" aria-current="page"
                               href="{% url 'authapp:login' %}">Авторизация</a>
                            <a class="nav-link number" aria-current="page" href="{% url 'authapp:register' %}">Регистрация</a>
                        {% else %}
                            <a class="nav-link number" aria-current="page" href="{% url 'authapp:login' %}">Корзина</a>
                            <a class="nav-link number" aria-current="page" href="{% url 'authapp:login' %}">Заказы</a>
                            <a class="nav-link number" aria-current="page" href="{% url 'authapp:logout' %}"><img
                                    class="exit" src="{% static 'img/icons8-выход-50.png' %}" alt="" width="30"
                                    height="30"></a>
                        {% endif %}
                    </div>
                </div>

            </div>
        </nav>
    </div>
</div>
<div class="container" style="margin-top: 90px">
    {% block content %}

    {% endblock %}
</div>
</div>
    <div id="map" class="map">
        <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A4d4a381788fd6f28f29538f1a79e4b52b392d5713c22b4a796360d9642051c75&amp;source=constructor"
                width="100%" height="700" frameborder="0"></iframe>
        <div class="cube3">
            <div class="tcube">
                <div class="text15">ХОТИТЕ ОБСУДИТЬ<br> ЗАКАЗ ЛИЧНО?</div>
                <div class="text17">Приезжайте к нам в офис:</div>
                <div class="text16">
                    Курганская область г.Курган<br> ул.Советская, д.51<br></div>
                <div class="text18"> Телефон: +7 3522 46-07-08</div>
                <div class="text19"> ОГРНИП 316450100051703</div>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="container">
            <div class="footer_link">
                <div class="linkfooter">
                    <a class="link" aria-current="page" href="#">Главная</a>
                    <a class="link" aria-current="page" href="#service">Услуги</a>
                    <a class="link" aria-current="page" href="#">Контакты</a>
                    <a class="link" aria-current="page" href="#o_nas">О нас</a>
                    <a class="link" aria-current="page">+7 3522 46-07-08</a>
                </div>
            </div>
        </div>
    </div>
</body>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</html>

mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
     <div class="element-animation">
                            <span>
    <div class="tblock">
        <h6 id="service" class="t6">Наши услуги</h6>
        <section class="row">
            {% for item in products %}
                <div class="col-md-4 col-sm-12 wrapper">
                    <div class="img-op">
                        <img src="{{ item.image.url }}" alt="{{ item.name|capfirst }}" width="359" height="229">
                    </div>
                    <div class="text">{{ item.name|capfirst }}</div>
                    <div class="price1">От {{ item.price }} руб</div>
                    <div class="d-flex justify-content-around">
                        <a href="{% url 'mainapp:info' item.id %}" class="b_order">
                            Заказать
                        </a>
                    </div>

                </div>
            {% endfor %}
        </section>
    </div>
                            </span>
     </div>
{% endblock %}

mainapp/templates/mainapp/info.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div class="col-md-4 col-sm-12 wrapper">
        <div class="img-op">
            <img src="{{ product.image.url }}" alt="{{ product.name|capfirst }}" width="359" height="229">
        </div>
        <div class="text">{{ product.name|capfirst }}</div>
        <div class="price1">От {{ product.price }} руб</div>
        <div class="d-flex justify-content-around">
            <a href="{% url 'mainapp:index' %}#z1" class="b_order">
                Заказать
            </a>
        </div>
    </div>
    <div class="info_on_product">{{ product.info|linebreaks }}</div>
{% endblock %}